//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamStudent.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_Form_Temp
    {
        public int Employee_ID { get; set; }
        public string Employee_Name { get; set; }
        public System.DateTime Emp_DOB { get; set; }
        public string Emp_MobileNumber { get; set; }
        public string Emp_Block { get; set; }
        public Nullable<int> PostID { get; set; }
        public string Emp_Password { get; set; }
        public string Emp_ConfirmPassword { get; set; }
        public int EmpStateID { get; set; }
        public int Emp_CityID { get; set; }
        public string Emp_EmailAddress { get; set; }
        public string Emp_AppID { get; set; }
        public string usercode { get; set; }
        public Nullable<int> RefferalID { get; set; }
        public string ReferlName { get; set; }
        public string ResetPasswordCode { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> SubjectID { get; set; }
        public Nullable<bool> isFeatured { get; set; }
        public string FranchiesCode { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<bool> IsPaid { get; set; }
        public Nullable<bool> IsApproved { get; set; }
    
        public virtual Emp_City Emp_City { get; set; }
        public virtual EmpState EmpState { get; set; }
        public virtual PostForm PostForm { get; set; }
        public virtual ReferalForm ReferalForm { get; set; }
    }
}
