//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamStudent.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExamResult
    {
        public int ExamResultID { get; set; }
        public int UserId { get; set; }
        public Nullable<System.DateTime> ExamDateTime { get; set; }
        public string Percentange { get; set; }
        public Nullable<long> AnswerCount { get; set; }
        public string AnswerIDs { get; set; }
    
        public virtual User User { get; set; }
    }
}
