//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamStudent.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Franchy
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> gstPercentage { get; set; }
        public Nullable<decimal> Transpercentage { get; set; }
        public string FranchiesName { get; set; }
    }
}
