//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamStudent.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MockQuestionBank
    {
        public int MockQuestionID { get; set; }
        public int QuestionID { get; set; }
        public int OptionIDA { get; set; }
        public int OptionIDB { get; set; }
        public int OptionIDC { get; set; }
        public int OptionIDD { get; set; }
    }
}
