//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamStudent.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReferalForm
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ReferalForm()
        {
            this.Employee_Form = new HashSet<Employee_Form>();
            this.Employee_Form_Temp = new HashSet<Employee_Form_Temp>();
        }
    
        public int RefferalID { get; set; }
        public string ReferalName { get; set; }
        public string RefferLid { get; set; }
        public string Employee_ID { get; set; }
        public string usercode { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> ReferEmpID { get; set; }
        public Nullable<int> ReferEmpCity { get; set; }
        public Nullable<int> RefereEmpState { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee_Form> Employee_Form { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee_Form_Temp> Employee_Form_Temp { get; set; }
    }
}
