//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamStudent.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Refer
    {
        public int ReferID { get; set; }
        public string UserID { get; set; }
        public string RefferLid { get; set; }
        public string usercode { get; set; }
        public string ReferalName { get; set; }
    }
}
