//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamStudent.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subject
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Subject()
        {
            this.Teachers = new HashSet<Teacher>();
        }
    
        public int SubjectID { get; set; }
        public string SubjectName { get; set; }
        public int StandardID { get; set; }
        public int BoardTypeID { get; set; }
        public int MediumID { get; set; }
        public string subjectDescription { get; set; }
        public Nullable<decimal> subjectPrice { get; set; }
        public string subjectDiscount { get; set; }
        public string subjectTotalHour { get; set; }
        public string ImageURL { get; set; }
        public string PDFFile { get; set; }
        public string VideoURL { get; set; }
        public string Comment { get; set; }
        public string CoverFilename { get; set; }
        public string CoverFilePath { get; set; }
        public string FileName { get; set; }
        public string FilePath { get; set; }
    
        public virtual BoardType BoardType { get; set; }
        public virtual Medium Medium { get; set; }
        public virtual Standard Standard { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Teacher> Teachers { get; set; }
    }
}
