//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamStudent.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tab_User_Info_Temp
    {
        public int Id { get; set; }
        public string ApplicationID { get; set; }
        public string Name { get; set; }
        public string EmailAddress { get; set; }
        public string MobileNumber { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<int> ReferID { get; set; }
        public string Password { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ConfirmPassword { get; set; }
        public Nullable<int> StateID { get; set; }
        public Nullable<int> CityID { get; set; }
        public string Block { get; set; }
        public string usercode { get; set; }
        public string ReferlName { get; set; }
        public Nullable<int> EmpID { get; set; }
        public Nullable<int> BoardTypeID { get; set; }
        public Nullable<int> MediumID { get; set; }
        public Nullable<int> StandardID { get; set; }
        public string ResetPasswordCode { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> BoardSecondID { get; set; }
        public Nullable<int> MediumSecondID { get; set; }
        public Nullable<int> StandardSecondID { get; set; }
        public Nullable<int> UserSubjectID { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<bool> IsPaid { get; set; }
        public Nullable<bool> IsApproved { get; set; }
    
        public virtual BoardType BoardType { get; set; }
        public virtual City City { get; set; }
        public virtual Medium Medium { get; set; }
        public virtual Standard Standard { get; set; }
        public virtual State State { get; set; }
    }
}
