//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamStudent.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TabPayumoneyTransectionLog
    {
        public int ID { get; set; }
        public System.DateTime Date { get; set; }
        public string FirstName { get; set; }
        public decimal Amount { get; set; }
        public string productInfo { get; set; }
        public string EmailAddress { get; set; }
        public string PhoneNumber { get; set; }
        public string TransectionID { get; set; }
        public Nullable<bool> IsPaid { get; set; }
        public string ApplicationID { get; set; }
    }
}
