//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamStudent.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teacher
    {
        public int TeacherId { get; set; }
        public string TeacherName { get; set; }
        public int BoardTypeID { get; set; }
        public int MediumID { get; set; }
        public int SubjectID { get; set; }
    
        public virtual BoardType BoardType { get; set; }
        public virtual Medium Medium { get; set; }
        public virtual Subject Subject { get; set; }
    }
}
