//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamStudent.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSubject
    {
        public int UserSubjectID { get; set; }
        public string SubjectName { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> StandardSecondID { get; set; }
        public Nullable<int> UserTempId { get; set; }
    
        public virtual StandardSecond StandardSecond { get; set; }
    }
}
